/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg160419113_fraction;

/**
 *
 * @author alif
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fract1Enum = new javax.swing.JTextField();
        fract1Denom = new javax.swing.JTextField();
        fract2Enum = new javax.swing.JTextField();
        fract2Denom = new javax.swing.JTextField();
        buttonDivide = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        fractResEnum = new javax.swing.JTextField();
        fractRestDenom = new javax.swing.JTextField();
        buttonMultiply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fract1Denom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fract1DenomActionPerformed(evt);
            }
        });

        buttonDivide.setText("/");
        buttonDivide.setActionCommand("buttonDivide");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });

        buttonPlus.setText("+");
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });

        buttonMinus.setText("-");
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        buttonMultiply.setText("X");
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(66, Short.MAX_VALUE)
                        .addComponent(buttonMultiply)
                        .addGap(28, 28, 28)
                        .addComponent(buttonDivide)
                        .addGap(40, 40, 40)
                        .addComponent(buttonPlus)
                        .addGap(30, 30, 30)
                        .addComponent(buttonMinus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fract1Denom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fract2Denom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fract1Enum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fract2Enum))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fractResEnum)
                                    .addComponent(fractRestDenom))
                                .addGap(72, 72, 72)))))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fract1Enum)
                    .addComponent(fract2Enum))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fract1Denom)
                    .addComponent(fract2Denom))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDivide)
                    .addComponent(buttonPlus)
                    .addComponent(buttonMinus)
                    .addComponent(buttonMultiply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(fractResEnum)
                .addGap(18, 18, 18)
                .addComponent(fractRestDenom)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        // TODO add your handling code here:
        
        
        
        Fraction fract1 = new Fraction(Double.parseDouble(fract1Enum.getText()) , Double.parseDouble(fract1Denom.getText()));
        Fraction fract2 = new Fraction(Double.parseDouble(fract2Enum.getText()) , Double.parseDouble(fract2Denom.getText()));
        
        Fraction fractResult = fract1.Multiply(fract2);
        
        fractResEnum.setText("");
        fractRestDenom.setText("");
        
        double resEnum = fractResult.getEnumerator();
        double resDenom = fractResult.getDenominator();
        fractResEnum.setText(String.valueOf(resEnum));
        fractRestDenom.setText(String.valueOf(resDenom));
        
        
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    private void fract1DenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fract1DenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fract1DenomActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        // TODO add your handling code here:
        
        
        Fraction fract1 = new Fraction(Double.parseDouble(fract1Enum.getText()) , Double.parseDouble(fract1Denom.getText()));
        Fraction fract2 = new Fraction(Double.parseDouble(fract2Enum.getText()) , Double.parseDouble(fract2Denom.getText()));
        
        Fraction fractResult = fract1.Division(fract2);
        
        fractResEnum.setText("");
        fractRestDenom.setText("");
        
        double resEnum = fractResult.getEnumerator();
        double resDenom = fractResult.getDenominator();
        fractResEnum.setText(String.valueOf(resEnum));
        fractRestDenom.setText(String.valueOf(resDenom));
    }//GEN-LAST:event_buttonDivideActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        // TODO add your handling code here:
        
        
        Fraction fract1 = new Fraction(Double.parseDouble(fract1Enum.getText()) , Double.parseDouble(fract1Denom.getText()));
        Fraction fract2 = new Fraction(Double.parseDouble(fract2Enum.getText()) , Double.parseDouble(fract2Denom.getText()));
        
        Fraction fractResult = fract1.Add(fract2);
        
        fractResEnum.setText("");
        fractRestDenom.setText("");
        
        double resEnum = fractResult.getEnumerator();
        double resDenom = fractResult.getDenominator();
        fractResEnum.setText(String.valueOf(resEnum));
        fractRestDenom.setText(String.valueOf(resDenom));
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        // TODO add your handling code here:
        
        
        Fraction fract1 = new Fraction(Double.parseDouble(fract1Enum.getText()) , Double.parseDouble(fract1Denom.getText()));
        Fraction fract2 = new Fraction(Double.parseDouble(fract2Enum.getText()) , Double.parseDouble(fract2Denom.getText()));
        
        Fraction fractResult = fract1.Substract(fract2);
        
        fractResEnum.setText("");
        fractRestDenom.setText("");
        
        double resEnum = fractResult.getEnumerator();
        double resDenom = fractResult.getDenominator();
        fractResEnum.setText(String.valueOf(resEnum));
        fractRestDenom.setText(String.valueOf(resDenom));
    }//GEN-LAST:event_buttonMinusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JTextField fract1Denom;
    private javax.swing.JTextField fract1Enum;
    private javax.swing.JTextField fract2Denom;
    private javax.swing.JTextField fract2Enum;
    private javax.swing.JTextField fractResEnum;
    private javax.swing.JTextField fractRestDenom;
    // End of variables declaration//GEN-END:variables
}
